baseURL = "https://tiwariji.net/"
languageCode = "en-us"
title = "AAYUSHYA TIWARI"
theme = "ananke"

[menu]

[[menu.main]]
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts/"
weight = 2

[params.ananke]
show_recent_posts = false
