baseURL = "https://tiwariji.net/"
languageCode = "en-us"
title = "AAYUSHYA"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


# [params.homeInfoParams]
#   Title = "AAYUSHYA"
#   Content = "Welcome to my technical blog"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

# [[menu.main]]
#   name = "Tags"
#   url = "/tags/"
#   weight = 3
