baseURL = "https://tiwariji.net/"
languageCode = "en-us"
title = "AAYUSHYA"
theme = "ananke"

[menu]

[[menu.main]]
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts/"
weight = 2
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.ananke]
show_recent_posts = false
